#! /usr/bin/zsh
# DERPlib		-*- mode:Makefile -*-
# Copyright (C) 2019-2020 Nathan Sidwell, nathan@acm.org
# License: LGPL v3.0 or later

pushd ${0%/*}
setopt nullglob
for subdir in $@ ; do
    echo $subdir/*(.^*)
done
popd
